CREATE TABLE COINS_MASTER (
   ID INT NOT NULL,
   COIN_TYPE FLOAT,
   COIN_DESC VARCHAR(255),
   COIN_COUNT INT NOT NULL
);

CREATE TABLE EXCHANGE_MASTER (
   ID INT NOT NULL,
   PREFERENCE FLOAT,
   DESCRIPTION VARCHAR(255),
   BILL_PRODUCED INT NOT NULL
);